export const CREATE_ROOM_ACTION_TYPE = "CREATE_ROOM_ACTION_TYPE";
export const SET_STEP_TYPE = "SET_STEP_TYPE";
export const UPDATE_GROUP_PROFILE = "UPDATE_GROUP_PROFILE";
export const UPDATE_GROUP_MEMBER_LIST = "UPDATE_GROUP_MEMBER_LIST";
export const UPDATE_FORM_STATE = "UPDATE_FORM_STATE";
export const UPDATE_USER_SIG = "UPDATE_USER_SIG";
export const ADD_MEET = "ADD_MEET";
